import { discordClientId, discordGuildId, discordRedirectUri } from "../../config.js";

const TOKEN_KEY = "hades_auth_token";

/**
 * Reads the stored JWT, or null when not in a browser.
 */
export function getToken(): string | null {
  if (typeof localStorage === "undefined") {
    return null;
  }
  return localStorage.getItem(TOKEN_KEY);
}

/**
 * Stores the JWT returned by discordLogin.
 */
export function setToken(token: string): void {
  if (typeof localStorage !== "undefined") {
    localStorage.setItem(TOKEN_KEY, token);
  }
}

/**
 * Clears the stored JWT.
 */
export function removeToken(): void {
  if (typeof localStorage !== "undefined") {
    localStorage.removeItem(TOKEN_KEY);
  }
}

/**
 * Builds the Discord OAuth authorize URL. The state nonce is generated by the
 * caller and verified (client-side) on the callback.
 */
export function discordAuthUrl(state: string): string {
  const params = new URLSearchParams({
    client_id: discordClientId,
    redirect_uri: discordRedirectUri,
    response_type: "code",
    scope: "identify guilds guilds.members.read",
    state,
  });
  return `https://discord.com/api/oauth2/authorize?${params.toString()}`;
}

/**
 * A random state nonce for the OAuth flow.
 */
export function newState(): string {
  return Math.random().toString(36).slice(2);
}

export { discordGuildId };
