import { ReaderAccount } from "~/generated/graphql.js";
import {
  discordClientId,
  discordGuildId,
  discordRedirectUri,
  discordScopes,
} from "../../config.js";
import { executeDocument } from "./api";
import {
  LoginDocument,
  ReaderAccountDocument,
  DiscordLoginDocument,
} from "~/generated/graphql";

const TOKEN_KEY = "hades_auth_token";

/**
 * Reads the stored JWT, or null when not in a browser.
 */
export function getToken(): string | null {
  if (typeof localStorage === "undefined") {
    return null;
  }
  return localStorage.getItem(TOKEN_KEY);
}

/**
 * Stores the JWT returned by discordLogin.
 */
export function setToken(token: string): void {
  if (typeof localStorage !== "undefined") {
    localStorage.setItem(TOKEN_KEY, token);
  }
}

/**
 * Clears the stored JWT.
 */
export function removeToken(): void {
  if (typeof localStorage !== "undefined") {
    localStorage.removeItem(TOKEN_KEY);
  }
}

/**
 * Builds the Discord OAuth authorize URL. The state nonce is generated by the
 * caller and verified (client-side) on the callback.
 */
export function discordAuthUrl(state: string): string {
  const params = new URLSearchParams({
    client_id: discordClientId,
    redirect_uri: discordRedirectUri,
    response_type: "code",
    scope: "identify guilds guilds.members.read",
    state,
  });
  return `https://discord.com/api/oauth2/authorize?${params.toString()}`;
}

/**
 * A random state nonce for the OAuth flow.
 */
export function newState(): string {
  return Math.random().toString(36).slice(2);
}

export { discordGuildId };

/**
 * Name of the httpOnly cookie holding the JWT.
 */
export const AUTH_COOKIE = "reader_auth";
/*
 * Short-lived cookie carrying the OAuth state nonce.
 */
export const OAUTH_STATE_COOKIE = "oauth_state";

/**
 * Reads a named cookie value from a raw Cookie header.
 */
export function getCookieValue(
  cookieHeader: string | undefined,
  name: string,
): string | undefined {
  if (!cookieHeader) return undefined;
  for (const part of cookieHeader.split(/;\s*/)) {
    const index = part.indexOf("=");
    if (index < 0) continue;
    if (part.slice(0, index).trim() === name) {
      return decodeURIComponent(part.slice(index + 1));
    }
  }
  return undefined;
}

/**
 * Builds the Set-Cookie value that stores the JWT.
 */
export function buildAuthCookie(
  token: string,
  maxAgeSeconds = 60 * 60 * 12,
): string {
  return `${AUTH_COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=${maxAgeSeconds}`;
}

/**
 * Builds the Set-Cookie value that clears the JWT.
 */
export function clearAuthCookie(): string {
  return `${AUTH_COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0`;
}

/**
 * Builds the Set-Cookie value for the OAuth state nonce.
 */
export function buildStateCookie(state: string): string {
  return `${OAUTH_STATE_COOKIE}=${encodeURIComponent(state)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=600`;
}

/**
 * A fresh OAuth state nonce.
 */
export function newOAuthState(): string {
  return crypto.randomUUID();
}

/**
 * Builds the Discord authorize URL the browser is redirected to.
 */
export function buildDiscordAuthUrl(state: string): string {
  const params = new URLSearchParams({
    client_id: discordClientId,
    redirect_uri: discordRedirectUri,
    response_type: "code",
    scope: discordScopes,
    state,
  });
  return `https://discord.com/api/oauth2/authorize?${params.toString()}`;
}

/**
 * Logs in via gaia and returns the JWT, or null if rejected.
 */
export async function loginViaGaia(
  username: string,
  password: string,
): Promise<string | null> {
  const res = await executeDocument<{
    gaiaMutations: { login: { token: string } | null };
  }>(LoginDocument, { input: { username, password } });
  if (!res.success || !res.data) {
    return null;
  }
  return res.data.gaiaMutations.login?.token ?? null;
}

/**
 * Returns the logged-in reader account for a JWT, or null.
 */
export async function getCurrentUser(
  token: string | undefined,
): Promise<ReaderAccount | null> {
  if (!token) {
    return null;
  }
  const res = await executeDocument<{
    hadesQueries: { readerAccount: ReaderAccount | null };
  }>(ReaderAccountDocument, {}, token);
  if (!res.success || !res.data) {
    return null;
  }
  return res.data.hadesQueries.readerAccount ?? null;
}

/**
 * Exchanges a Discord code for a JWT, or null on failure.
 */
export async function discordLoginViaCode(
  code: string,
  state: string,
): Promise<string | null> {
  const res = await executeDocument<{
    hadesMutations: { discordLogin: { token: string } | null };
  }>(DiscordLoginDocument, { code, state });
  if (!res.success || !res.data) {
    return null;
  }
  return res.data.hadesMutations.discordLogin?.token ?? null;
}
